/** Single-writer action classes (spec §Action classification):
 * - CANONICAL: mutates `character`; leader-executed; followers forward as intents.
 * - LOCAL_UI: tab-local flags; always executes locally.
 * - EXTERNAL_APPLY: wholesale adoption/replacement paths; always local, never forwarded.
 * - QUERY: read-only / value-returning; always local.
 * A unit test iterates the live store and fails on any unclassified function —
 * adding a store action REQUIRES adding it here. */
export type ActionClass = 'CANONICAL' | 'LOCAL_UI' | 'EXTERNAL_APPLY' | 'QUERY';

export const CHARACTER_ACTION_CLASSIFICATION: Record<string, ActionClass> = {
  // — core sheet edits —
  updateCharacter: 'CANONICAL',
  updateAbilityScore: 'CANONICAL',
  updateSkillProficiency: 'CANONICAL',
  updateSkillExpertise: 'CANONICAL',
  toggleSkillBonusAbility: 'CANONICAL',
  updateSavingThrowProficiency: 'CANONICAL',
  updateHitPoints: 'CANONICAL',
  updateInitiative: 'CANONICAL',
  resetInitiativeToDefault: 'CANONICAL',
  toggleReaction: 'CANONICAL',
  resetReaction: 'CANONICAL',
  toggleJackOfAllTrades: 'CANONICAL',
  // — heroic inspiration —
  updateHeroicInspiration: 'CANONICAL',
  addHeroicInspiration: 'CANONICAL',
  useHeroicInspiration: 'CANONICAL',
  resetHeroicInspiration: 'CANONICAL',
  setStackableInspiration: 'CANONICAL',
  // — class resources / cantrips —
  useClassResource: 'CANONICAL',
  restoreClassResource: 'CANONICAL',
  resetClassResource: 'CANONICAL',
  backfillCantripScaling: 'CANONICAL',
  // — armor class —
  updateTempArmorClass: 'CANONICAL',
  toggleTempAC: 'CANONICAL',
  toggleShield: 'CANONICAL',
  setTempACActive: 'CANONICAL',
  setShieldEquipped: 'CANONICAL',
  resetTempArmorClass: 'CANONICAL',
  updateShieldBonus: 'CANONICAL',
  // — HP / death —
  applyDamageToCharacter: 'CANONICAL',
  applyHealingToCharacter: 'CANONICAL',
  addTemporaryHPToCharacter: 'CANONICAL',
  makeDeathSavingThrow: 'CANONICAL',
  resetDeathSavingThrows: 'CANONICAL',
  toggleHPCalculationMode: 'CANONICAL',
  recalculateMaxHP: 'CANONICAL',
  // — class / level / spell slots —
  updateClass: 'CANONICAL',
  updateLevel: 'CANONICAL',
  updateSpellSlot: 'CANONICAL',
  updatePactMagicSlot: 'CANONICAL',
  resetSpellSlots: 'CANONICAL',
  resetPactMagicSlots: 'CANONICAL',
  spendSpellSlot: 'CANONICAL',
  restoreSpellSlot: 'CANONICAL',
  spendPactMagicSlot: 'CANONICAL',
  restorePactMagicSlot: 'CANONICAL',
  addClassLevel: 'CANONICAL',
  removeClassLevel: 'CANONICAL',
  updateClassLevel: 'CANONICAL',
  // — hit dice —
  useHitDie: 'CANONICAL',
  restoreHitDice: 'CANONICAL',
  resetAllHitDice: 'CANONICAL',
  resetHalfHitDice: 'CANONICAL', // creator-only (missing from interface — pre-existing)
  // — concentration —
  startConcentration: 'CANONICAL',
  stopConcentration: 'CANONICAL',
  // — conditions / diseases —
  addCondition: 'CANONICAL',
  updateCondition: 'CANONICAL',
  removeCondition: 'CANONICAL',
  addDisease: 'CANONICAL',
  updateDisease: 'CANONICAL',
  removeDisease: 'CANONICAL',
  setExhaustionVariant: 'CANONICAL',
  clearAllConditions: 'CANONICAL',
  clearAllDiseases: 'CANONICAL',
  // — XP —
  addExperience: 'CANONICAL',
  setExperience: 'CANONICAL',
  // — rich text —
  addFeature: 'CANONICAL',
  updateFeature: 'CANONICAL',
  deleteFeature: 'CANONICAL',
  addTrait: 'CANONICAL',
  updateTrait: 'CANONICAL',
  deleteTrait: 'CANONICAL',
  addNote: 'CANONICAL',
  updateNote: 'CANONICAL',
  deleteNote: 'CANONICAL',
  reorderNotes: 'CANONICAL',
  // — trackable traits / extended features —
  addTrackableTrait: 'CANONICAL',
  updateTrackableTrait: 'CANONICAL',
  deleteTrackableTrait: 'CANONICAL',
  useTrackableTrait: 'CANONICAL',
  resetTrackableTraits: 'CANONICAL',
  addExtendedFeature: 'CANONICAL',
  updateExtendedFeature: 'CANONICAL',
  deleteExtendedFeature: 'CANONICAL',
  useExtendedFeature: 'CANONICAL',
  resetExtendedFeatures: 'CANONICAL',
  reorderExtendedFeatures: 'CANONICAL',
  toggleFavoriteFeature: 'CANONICAL',
  migrateTraitsToExtendedFeatures: 'CANONICAL',
  // — languages / tools / immunities / senses —
  addLanguage: 'CANONICAL',
  deleteLanguage: 'CANONICAL',
  addToolProficiency: 'CANONICAL',
  updateToolProficiency: 'CANONICAL',
  deleteToolProficiency: 'CANONICAL',
  addDamageImmunity: 'CANONICAL',
  removeDamageImmunity: 'CANONICAL',
  addDamageResistance: 'CANONICAL',
  removeDamageResistance: 'CANONICAL',
  addConditionImmunity: 'CANONICAL',
  removeConditionImmunity: 'CANONICAL',
  addSense: 'CANONICAL',
  updateSense: 'CANONICAL',
  removeSense: 'CANONICAL',
  // — buffs —
  addBuff: 'CANONICAL',
  updateBuff: 'CANONICAL',
  deleteBuff: 'CANONICAL',
  toggleBuff: 'CANONICAL',
  clearAllBuffs: 'CANONICAL',
  // — rest / campaign —
  takeShortRest: 'CANONICAL',
  takeLongRest: 'CANONICAL',
  updateDaysSpent: 'CANONICAL',
  incrementDaysSpent: 'CANONICAL',
  toggleShareHpWithParty: 'CANONICAL',
  updateCharacterBackground: 'CANONICAL',
  // — weapons —
  addWeapon: 'CANONICAL',
  updateWeapon: 'CANONICAL',
  deleteWeapon: 'CANONICAL',
  equipWeapon: 'CANONICAL',
  reorderWeapons: 'CANONICAL',
  expendWeaponCharge: 'CANONICAL',
  restoreWeaponCharge: 'CANONICAL',
  setWeaponChargeUsed: 'CANONICAL',
  expendWeaponChargePoolAbility: 'CANONICAL',
  restoreWeaponChargePool: 'CANONICAL',
  setWeaponChargePoolUsed: 'CANONICAL',
  // — magic items —
  addMagicItem: 'CANONICAL',
  updateMagicItem: 'CANONICAL',
  deleteMagicItem: 'CANONICAL',
  attuneMagicItem: 'CANONICAL',
  updateAttunementSlots: 'CANONICAL',
  reorderMagicItems: 'CANONICAL',
  expendMagicItemCharge: 'CANONICAL',
  restoreMagicItemCharge: 'CANONICAL',
  setMagicItemChargeUsed: 'CANONICAL',
  expendChargePoolAbility: 'CANONICAL',
  restoreChargePool: 'CANONICAL',
  setChargePoolUsed: 'CANONICAL',
  // — armor / inventory / currency —
  addArmorItem: 'CANONICAL',
  updateArmorItem: 'CANONICAL',
  deleteArmorItem: 'CANONICAL',
  equipArmorItem: 'CANONICAL',
  reorderArmorItems: 'CANONICAL',
  addInventoryItem: 'CANONICAL',
  updateInventoryItem: 'CANONICAL',
  deleteInventoryItem: 'CANONICAL',
  updateItemQuantity: 'CANONICAL',
  reorderInventoryItems: 'CANONICAL',
  updateCurrency: 'CANONICAL',
  addCurrency: 'CANONICAL',
  subtractCurrency: 'CANONICAL',
  // — spellbook —
  addSpellToSpellbook: 'CANONICAL',
  removeSpellFromSpellbook: 'CANONICAL',
  toggleSpellFavorite: 'CANONICAL',
  prepareSpell: 'CANONICAL',
  unprepareSpell: 'CANONICAL',
  updateSpellbookSettings: 'CANONICAL',
  addCustomSpell: 'CANONICAL',
  removeCustomSpell: 'CANONICAL',
  reorderPreparedSpells: 'CANONICAL',
  reorderSpells: 'CANONICAL',
  // — summons / saved creatures —
  addSummon: 'CANONICAL',
  removeSummon: 'CANONICAL',
  updateSummonEntity: 'CANONICAL',
  damageSummon: 'CANONICAL',
  healSummon: 'CANONICAL',
  addSummonTempHp: 'CANONICAL',
  addSummonCondition: 'CANONICAL',
  removeSummonCondition: 'CANONICAL',
  removeConcentrationSummons: 'CANONICAL',
  dismissFamiliar: 'CANONICAL',
  addSavedCreature: 'CANONICAL',
  updateSavedCreature: 'CANONICAL',
  removeSavedCreature: 'CANONICAL',
  // — wholesale replacement / adoption (always local) —
  loadCharacterState: 'EXTERNAL_APPLY',
  loadCharacter: 'EXTERNAL_APPLY',
  importCharacter: 'EXTERNAL_APPLY',
  resetCharacter: 'EXTERNAL_APPLY',
  // — tab-local UI —
  saveCharacter: 'LOCAL_UI',
  setSaveStatus: 'LOCAL_UI',
  markSaved: 'LOCAL_UI',
  markUnsaved: 'LOCAL_UI',
  clearDeathAnimation: 'LOCAL_UI',
  clearLevelUpAnimation: 'LOCAL_UI',
  noteIntentApplied: 'LOCAL_UI',
  triggerDeathAnimation: 'LOCAL_UI',
  triggerLevelUpAnimation: 'LOCAL_UI',
  // — queries —
  isMulticlassed: 'QUERY',
  getClassDisplayString: 'QUERY',
  isConcentratingOn: 'QUERY',
  exportCharacter: 'QUERY',
};
