import {
  Anchor,
  Angry,
  Axe,
  Ban,
  BatteryLow,
  Bed,
  Beer,
  Biohazard,
  Bomb,
  Bone,
  Brain,
  Bug,
  ChevronsDown,
  ChevronsUp,
  CircleDashed,
  CircleDot,
  CloudFog,
  CloudLightning,
  Cross,
  Crosshair,
  Crown,
  Droplet,
  Ear,
  EarOff,
  Eclipse,
  Expand,
  Eye,
  EyeOff,
  Flame,
  FlaskConical,
  Footprints,
  Frown,
  Ghost,
  Grab,
  Hand,
  HandFist,
  Heart,
  HeartCrack,
  HeartPulse,
  Hourglass,
  Infinity as InfinityIcon,
  Laugh,
  Leaf,
  Link,
  Lock,
  Magnet,
  Moon,
  MoonStar,
  Mountain,
  Music,
  Orbit,
  PawPrint,
  Rabbit,
  Radiation,
  Shield,
  ShieldAlert,
  ShieldOff,
  ShieldPlus,
  Shrink,
  Skull,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Sword,
  Swords,
  Syringe,
  Target,
  ThermometerSnowflake,
  ThermometerSun,
  Tornado,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Turtle,
  VolumeX,
  WandSparkles,
  Waves,
  Wind,
  Zap,
} from 'lucide-react';

import type { LucideIcon } from 'lucide-react';

/**
 * Curated, thematic lucide icons a DM may assign to a custom condition.
 * Kebab-case lucide names (same convention as ClassResourceIcon). Deliberately
 * NOT the full lucide library: every entry is statically imported so nothing
 * is loaded dynamically, and the tuple doubles as the sync-boundary allowlist.
 */
export const CONDITION_ICON_NAMES = [
  // Harm, poison, disease
  'skull',
  'bone',
  'heart-crack',
  'heart',
  'heart-pulse',
  'droplet',
  'syringe',
  'biohazard',
  'radiation',
  'bug',
  'flask-conical',
  // Elements and nature
  'flame',
  'snowflake',
  'zap',
  'cloud-lightning',
  'cloud-fog',
  'wind',
  'tornado',
  'waves',
  'mountain',
  'leaf',
  'sun',
  'moon',
  'moon-star',
  'eclipse',
  'thermometer-snowflake',
  'thermometer-sun',
  // Senses and mind
  'eye',
  'eye-off',
  'ear',
  'ear-off',
  'volume-x',
  'brain',
  'ghost',
  'angry',
  'frown',
  'laugh',
  'bed',
  // Control and movement
  'link',
  'anchor',
  'lock',
  'grab',
  'hand',
  'hand-fist',
  'footprints',
  'magnet',
  'ban',
  'circle-dashed',
  'circle-dot',
  'chevrons-down',
  'chevrons-up',
  'trending-down',
  'trending-up',
  'turtle',
  'rabbit',
  'shrink',
  'expand',
  // Combat and defence
  'shield',
  'shield-off',
  'shield-alert',
  'shield-plus',
  'sword',
  'swords',
  'axe',
  'crosshair',
  'target',
  'bomb',
  'triangle-alert',
  // Magic and misc
  'sparkles',
  'wand-sparkles',
  'star',
  'crown',
  'music',
  'hourglass',
  'battery-low',
  'beer',
  'paw-print',
  'orbit',
  'cross',
  'infinity',
] as const;

export type ConditionIconName = (typeof CONDITION_ICON_NAMES)[number];

export const CONDITION_ICON_REGISTRY: Record<ConditionIconName, LucideIcon> = {
  skull: Skull,
  bone: Bone,
  'heart-crack': HeartCrack,
  heart: Heart,
  'heart-pulse': HeartPulse,
  droplet: Droplet,
  syringe: Syringe,
  biohazard: Biohazard,
  radiation: Radiation,
  bug: Bug,
  'flask-conical': FlaskConical,
  flame: Flame,
  snowflake: Snowflake,
  zap: Zap,
  'cloud-lightning': CloudLightning,
  'cloud-fog': CloudFog,
  wind: Wind,
  tornado: Tornado,
  waves: Waves,
  mountain: Mountain,
  leaf: Leaf,
  sun: Sun,
  moon: Moon,
  'moon-star': MoonStar,
  eclipse: Eclipse,
  'thermometer-snowflake': ThermometerSnowflake,
  'thermometer-sun': ThermometerSun,
  eye: Eye,
  'eye-off': EyeOff,
  ear: Ear,
  'ear-off': EarOff,
  'volume-x': VolumeX,
  brain: Brain,
  ghost: Ghost,
  angry: Angry,
  frown: Frown,
  laugh: Laugh,
  bed: Bed,
  link: Link,
  anchor: Anchor,
  lock: Lock,
  grab: Grab,
  hand: Hand,
  'hand-fist': HandFist,
  footprints: Footprints,
  magnet: Magnet,
  ban: Ban,
  'circle-dashed': CircleDashed,
  'circle-dot': CircleDot,
  'chevrons-down': ChevronsDown,
  'chevrons-up': ChevronsUp,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  turtle: Turtle,
  rabbit: Rabbit,
  shrink: Shrink,
  expand: Expand,
  shield: Shield,
  'shield-off': ShieldOff,
  'shield-alert': ShieldAlert,
  'shield-plus': ShieldPlus,
  sword: Sword,
  swords: Swords,
  axe: Axe,
  crosshair: Crosshair,
  target: Target,
  bomb: Bomb,
  'triangle-alert': TriangleAlert,
  sparkles: Sparkles,
  'wand-sparkles': WandSparkles,
  star: Star,
  crown: Crown,
  music: Music,
  hourglass: Hourglass,
  'battery-low': BatteryLow,
  beer: Beer,
  'paw-print': PawPrint,
  orbit: Orbit,
  cross: Cross,
  infinity: InfinityIcon,
};

const CONDITION_ICON_NAME_SET: ReadonlySet<string> = new Set(
  CONDITION_ICON_NAMES
);

/** Sync/persistence boundary guard: unknown strings degrade to the fallback icon. */
export function isConditionIconName(
  value: unknown
): value is ConditionIconName {
  return typeof value === 'string' && CONDITION_ICON_NAME_SET.has(value);
}

/** Matches KIND_FALLBACK in conditionIcons.ts so a defaulted icon looks unchanged. */
export const DEFAULT_CONDITION_ICON_BY_KIND: Record<
  'buff' | 'debuff' | 'neutral',
  ConditionIconName
> = {
  buff: 'trending-up',
  debuff: 'trending-down',
  neutral: 'circle-dot',
};
