import {
  AlertTriangle,
  Anvil,
  Backpack,
  Ban,
  BookOpen,
  Brain,
  CalendarDays,
  Cloud,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudRain,
  CloudSun,
  Check,
  CircleHelp,
  Coins,
  Crosshair,
  Dice6,
  Eye,
  Flame,
  Gem,
  Hammer,
  Heart,
  HeartCrack,
  Lightbulb,
  LoaderCircle,
  Map,
  MapPin,
  Moon,
  Package,
  PawPrint,
  RotateCcw,
  ScrollText,
  Shield,
  Skull,
  Sparkles,
  Star,
  Sun,
  Snowflake,
  Swords,
  Target,
  Telescope,
  ThermometerSnowflake,
  ThermometerSun,
  Trash2,
  TrendingUp,
  User,
  Users,
  WandSparkles,
  Wind,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { LevelUpIcon } from './customIcons';

/**
 * Canonical semantic icons for RollKeeper.
 *
 * Call sites use meanings, not Lucide component names. This keeps a concept
 * visually consistent and makes changing it a one-line edit here.
 */
export const ICONS = {
  abilities: Zap,
  armor: Shield,
  attack: Swords,
  calendar: CalendarDays,
  character: User,
  concentration: Brain,
  confirm: Check,
  criticalFailure: HeartCrack,
  criticalSuccess: Star,
  currency: Coins,
  damage: Flame,
  dice: Dice6,
  error: AlertTriangle,
  experience: TrendingUp,
  features: ScrollText,
  healing: Heart,
  inspiration: Sparkles,
  inventory: Backpack,
  item: Package,
  levelUp: LevelUpIcon,
  location: MapPin,
  magicItem: Gem,
  map: Map,
  monster: Skull,
  party: Users,
  proficiencies: Wrench,
  prohibited: Ban,
  rangedAttack: Crosshair,
  reaction: Zap,
  ritual: Flame,
  reset: RotateCcw,
  restLong: Moon,
  restShort: Sun,
  save: Shield,
  search: Telescope,
  spell: WandSparkles,
  spellbook: BookOpen,
  summon: PawPrint,
  target: Target,
  tool: Hammer,
  tip: Lightbulb,
  loading: LoaderCircle,
  delete: Trash2,
  unknown: CircleHelp,
  visibility: Eye,
  weapon: Swords,
  weaponCraft: Anvil,
  weatherClear: Sun,
  weatherCloudy: CloudSun,
  weatherOvercast: Cloud,
  weatherFog: CloudFog,
  weatherRain: CloudRain,
  weatherHeavyRain: CloudRain,
  weatherStorm: CloudLightning,
  weatherSnow: Snowflake,
  weatherBlizzard: Wind,
  weatherHail: CloudHail,
  weatherHot: ThermometerSun,
  weatherCold: ThermometerSnowflake,
  weatherWind: Wind,
  remove: X,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export const SPELL_SCHOOL_ICONS = {
  Abjuration: 'armor',
  Conjuration: 'summon',
  Divination: 'visibility',
  Enchantment: 'inspiration',
  Evocation: 'damage',
  Illusion: 'inspiration',
  Necromancy: 'monster',
  Transmutation: 'reset',
} as const satisfies Record<string, IconName>;

export const ITEM_CATEGORY_ICONS = {
  weapon: 'weapon',
  armor: 'armor',
  tool: 'tool',
  misc: 'item',
  magic: 'magicItem',
  consumable: 'healing',
  treasure: 'magicItem',
} as const satisfies Record<string, IconName>;

export const MAGIC_ITEM_CATEGORY_ICONS = {
  wondrous: 'magicItem',
  ring: 'magicItem',
  wand: 'spell',
  staff: 'spell',
  rod: 'spell',
  armor: 'armor',
  shield: 'armor',
  potion: 'healing',
  scroll: 'features',
  artifact: 'magicItem',
  other: 'item',
} as const satisfies Record<string, IconName>;

export const WEATHER_ICONS = {
  clear: 'weatherClear',
  cloudy: 'weatherCloudy',
  overcast: 'weatherOvercast',
  fog: 'weatherFog',
  rain: 'weatherRain',
  'heavy-rain': 'weatherHeavyRain',
  thunderstorm: 'weatherStorm',
  snow: 'weatherSnow',
  blizzard: 'weatherBlizzard',
  hail: 'weatherHail',
  wind: 'weatherWind',
  hot: 'weatherHot',
  cold: 'weatherCold',
} as const satisfies Record<string, IconName>;

export const REFERENCE_ICONS = {
  item: 'item',
  spell: 'spell',
  filter: 'search',
  dice: 'dice',
  creature: 'monster',
  condition: 'inspiration',
  action: 'abilities',
  skill: 'target',
  sense: 'visibility',
  damage: 'damage',
  scaledamage: 'experience',
  atk: 'attack',
  atkr: 'rangedAttack',
  hit: 'target',
  h: 'damage',
  dc: 'save',
  actSave: 'save',
  actSaveFail: 'remove',
  actSaveSuccess: 'confirm',
  actTrigger: 'reaction',
  actResponse: 'reaction',
  hitYourSpellAttack: 'spell',
  unknown: 'unknown',
} as const satisfies Record<string, IconName>;

export function getIconName<T extends string>(
  mapping: Partial<Record<T, IconName>>,
  value: T | null | undefined,
  fallback: IconName = 'unknown'
): IconName {
  return (value && mapping[value]) || fallback;
}
